app_name: hermes
database_driver: sqlite
sqlite:
  file: hermes
  max_open_connection: "20"
  max_idle_connection: "10"

server:
  port: 10000

loggers:
  business:
    enabled: true
    level: debug
    format: text
    outputs:
      - type: stdout
  sql:
    enabled: true
    level: debug
    format: json
    outputs:
      - type: file
        file:
          filename: logs/sql.log
          max_size: "10M"
          max_backups: 5
          max_age: "7d"
          compress: true
